version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: dotnet pack Wibblr.Collections\Wibblr.Collections.csproj
artifacts:
- path: '**\*.nupkg'
