using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Wibblr.Collections;

namespace Wibblr.Metrics.Core
{
    /// <summary>
    /// Sink used for writing metrics to files. The serialization format (e.g. json, csv)
    /// is handled by an external serializer, and the file name is generated by an external class.
    /// </summary>
    public class FileSink : IMetricsSink
    {
        private IMetricsSerializer serializer;
        private IFileNamingStrategy fileNamingStrategy;

        public FileSink(IMetricsSerializer serializer, IFileNamingStrategy fileNamingStrategy)
        {
            this.serializer = serializer;
            this.fileNamingStrategy = fileNamingStrategy;
        }

        public void Flush(IEnumerable<WindowedCounter> counters)
        {
            foreach (var partition in counters.Partition((a, b) => !fileNamingStrategy.EqualNames(a, b)))
            {
                var fileName = fileNamingStrategy.BaseName(partition.First()) + "." + serializer.FileExtension;
                using (var w = CreateOrOpen(fileName, writer => serializer.WriteCounterHeader(writer)))
                    serializer.Write(partition, w);
            }
        }

        public void Flush(IEnumerable<WindowedBucket> buckets)
        {
            foreach (var partition in buckets.Partition((a, b) => !fileNamingStrategy.EqualNames(a, b)))
            {
                var fileName = fileNamingStrategy.BaseName(partition.First()) + "." + serializer.FileExtension;
                using (var w = CreateOrOpen(fileName, writer => serializer.WriteBucketHeader(writer)))
                    serializer.Write(partition, w);
            }
        }

        public void Flush(IEnumerable<TimestampedEvent> events)
        {
            foreach (var partition in events.Partition((a, b) => !fileNamingStrategy.EqualNames(a, b)))
            {
                var fileName = fileNamingStrategy.BaseName(partition.First()) + "." + serializer.FileExtension;
                using (var w = CreateOrOpen(fileName, writer => serializer.WriteEventHeader(writer)))
                    serializer.Write(partition, w);
            }
        }

        public void Flush(IEnumerable<Profile> profiles)
        {
            foreach (var partition in profiles.Partition((a, b) => !fileNamingStrategy.EqualNames(a, b)))
            {
                var fileName = fileNamingStrategy.BaseName(partition.First()) + "." + serializer.FileExtension;
                using (var w = CreateOrOpen(fileName, writer => serializer.WriteProfileHeader(writer)))
                {
                    serializer.Write(partition, w);
                }
            }
        }

        /// <summary>
        /// Open a file, or create it if it does not exist.
        /// If creating the file, execute the OnCreate action; if opening the file
        /// then seek to the end so that writes will append.
        /// </summary>
        /// <param name="fileName">Name of file</param>
        /// <param name="OnCreate">Action to execute if file was created</param>
        /// <returns></returns>
        private StreamWriter CreateOrOpen(string fileName, Action<TextWriter> OnCreate)
        {
            var stream = new FileStream(fileName, FileMode.OpenOrCreate, FileAccess.ReadWrite);
            var writer = new StreamWriter(stream);

            var len = stream.Length;

            if (len == 0)
                OnCreate(writer);
            else
                stream.Seek(len, SeekOrigin.Begin);
            
            return writer;
        }
    }
}
